[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1,<1",
    "google-genai>=2.18.1",
    "ipykernel>=7.3.0",
    "pydantic>=2.12.5,<3",
    "pydantic-settings>=2.15.0,<3",
    "supabase>=2.31.0,<3",
    "supabase-auth>=2.31.0,<3",
]
